---
- name: install build-essential packages for docker 
  apt:
    name: build-essential
    state: present
    update_cache: true

- name: install prerequisite packages for docker 
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - ca-certificates
    - curl
    - make
    - vim
    - lsb-release
    - wget
    - lvm2
    - python3-docker

- name: remove old docker gpg 
  file:
    path: /etc/apt/keyrings/docker.gpg
    state: absent

- name: add docker gpg
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: add docker repo
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    
- name: install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin